#!/bin/bash
# Runs once on first Postgres container start.
# Creates DB users and schemas for every module.
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Center
    CREATE USER center WITH PASSWORD '${CENTER_DB_PASSWORD}';
    CREATE SCHEMA IF NOT EXISTS center;
    GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO center;
    GRANT USAGE, CREATE ON SCHEMA center TO center;
    ALTER DEFAULT PRIVILEGES IN SCHEMA center GRANT ALL ON TABLES TO center;
    ALTER DEFAULT PRIVILEGES IN SCHEMA center GRANT ALL ON SEQUENCES TO center;

    -- Manhwa module
    CREATE USER manhwa WITH PASSWORD '${MANHWA_DB_PASSWORD}';
    CREATE SCHEMA IF NOT EXISTS manhwa;
    GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO manhwa;
    GRANT USAGE, CREATE ON SCHEMA manhwa TO manhwa;
    ALTER DEFAULT PRIVILEGES IN SCHEMA manhwa GRANT ALL ON TABLES TO manhwa;
    ALTER DEFAULT PRIVILEGES IN SCHEMA manhwa GRANT ALL ON SEQUENCES TO manhwa;

    -- Meals module
    CREATE USER meals WITH PASSWORD '${MEALS_DB_PASSWORD}';
    CREATE SCHEMA IF NOT EXISTS meals;
    GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO meals;
    GRANT USAGE, CREATE ON SCHEMA meals TO meals;
    ALTER DEFAULT PRIVILEGES IN SCHEMA meals GRANT ALL ON TABLES TO meals;
    ALTER DEFAULT PRIVILEGES IN SCHEMA meals GRANT ALL ON SEQUENCES TO meals;

    -- Pantry module
    CREATE USER pantry WITH PASSWORD '${PANTRY_DB_PASSWORD}';
    CREATE SCHEMA IF NOT EXISTS pantry;
    GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO pantry;
    GRANT USAGE, CREATE ON SCHEMA pantry TO pantry;
    ALTER DEFAULT PRIVILEGES IN SCHEMA pantry GRANT ALL ON TABLES TO pantry;
    ALTER DEFAULT PRIVILEGES IN SCHEMA pantry GRANT ALL ON SEQUENCES TO pantry;
EOSQL
